### PR TITLE
Team page

### PR DESCRIPTION
**Pull request by Im-Freeze**

### CODE REVIEW

**Comment by Pan-cakse** [comment]
How do you access the page? Fix that and ill merge it.

**Comment by Im-Freeze** [comment]
ima test just to see rq i need to make sure my twig code is working

**Comment by Pan-cakse** [comment]
image

**Comment by Im-Freeze** [comment]
ik ima fix it

**Comment by Pan-cakse** [comment]
you have to change layout.twig

**Comment by Im-Freeze** [comment]
i know im doing rn

**Pull request closed without merging**
