### PR TITLE
Team page (With topbar added)

### PR DESCRIPTION
**Pull request by Im-Freeze**

### CODE REVIEW

**Comment by Pan-cakse** [comment]
bruh 
image

**Comment by Im-Freeze** [comment]
idk how tf that happend

**Comment by Pan-cakse** [comment]
also the page doesnt work ... 
image

**Comment by Im-Freeze** [comment]
rip forgot the add json path

**Comment by Pan-cakse** [comment]
fix it and ill merge 
and how tf did you do that

**Comment by Im-Freeze** [comment]
i forgot to add json conntroler

**Pull request closed without merging**
